// Esse codigo detecta um problema usando o try-catch
// Ele exemplifica a chamada de uma função sincrona


function minhaFuncao ()
{
    
    return A;

}

try {
    minhaFuncao();
}
catch (e)
{
  console.log('detectou problema na funcao');
}
